[.NET] Card 01 - CRUD de Customer
guilhermeqmaia/CustomerAPI pull request #1
Opened 2022-11-18 13:03 UTC by guilhermeqmaia

- Criação de CRUD para entidade Customer
- Uso de Interface ICustomerService para métodos da classe CustomerService
- LifeTime Singleton para lista em memória da classe CustomerService
- FluentValidator de Customer realiza a validação automática
- StringExtensions para formatar valores como: Cpf, PostalCode(CEP) e Cellphone
- Métodos da classe CustomerController retornando IActionResult de acordo com sugerido na descrição do Card
- Uso de try/catch para capturar exceções em CustomerController

2022-11-18 13:21 UTC, santosclaudinei-warren commented on CustomerApplication/Controllers/CustomerController.cs
> +using Microsoft.AspNetCore.Http;
Não estão sendo utilizados.

2022-11-18 13:23 UTC, santosclaudinei-warren commented on CustomerApplication/Controllers/CustomerController.cs
> +            } catch (ArgumentException exception)
```suggestion
            } 
            catch(ArgumentNullException exception) {
                return NotFound(exception.Message);
            }
             catch (ArgumentException exception) 
```

2022-11-18 13:25 UTC, santosclaudinei-warren commented on CustomerApplication/Controllers/CustomerController.cs
> +            }
Em qual situação cairia nesse catch?

2022-11-18 13:27 UTC, santosclaudinei-warren commented on CustomerApplication/Controllers/CustomerController.cs
> +                return Created("Customer created with success", customer);
Deveria retornar o Id do customer caso ele fosse criado com sucesso.

2022-11-18 13:33 UTC, guilhermeqmaia commented on CustomerApplication/Controllers/CustomerController.cs
> +                return Created("Customer created with success", customer);
feito

2022-11-18 15:18 UTC, gregoryzimmerwarren reviewed
Deixei alguns comentários. Qualquer dúvida estou a disposição.

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +                throw new ArgumentException($"Customer with cpf {customer.Cpf} already exists");
```suggestion
            var customerIndex = _customers.FindIndex(tempCustomer => tempCustomer.Id == customer.Id);
            
            if (customerIndex == -1)
                throw new ArgumentNullException($"No customer with id: {customer.Id} was found in our database.");
            
            if (_customers.Any((tempCustomer) => tempCustomer.Email == customer.Email && tempCustomer.Id != customer.Id))
                throw new ArgumentException($"Customer with email: {customer.Email} already exists");
                
            if (_customers.Any((tempCustomer) => tempCustomer.Cpf == customer.Cpf && tempCustomer.Id != customer.Id))
                throw new ArgumentException($"Customer with cpf: {customer.Cpf} already exists");
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +        {
```suggestion
            RuleFor(customer => customer.Fullname)
                .NotEmpty()
                .MinimumLength(5);
                
            RuleFor(customer => customer.Email)
                .NotEmpty()
                .Equal(customer => customer.EmailConfirmation)
                .WithMessage("Emails don't match")
                .EmailAddress(EmailValidationMode.AspNetCoreCompatible)
                .WithMessage("Email is not valid");
                
            RuleFor(customer => customer.Cpf)
                .NotEmpty()
                .Must(validateCpf)
                .WithMessage("Invalid CPF");
                
            RuleFor(customer => customer.Cellphone)
                .NotEmpty()
                .Must(validateCellphone)
                .WithMessage("Cellphone is not valid, make sure that you provided a correct number");
                
            RuleFor(customer => customer.DateOfBirth)
                .NotEmpty()
                .WithMessage("Date of birth is not valid");
                
            RuleFor(customer => customer.Country)
                .NotEmpty();
                
            RuleFor(customer => customer.City)
                .NotEmpty();
                
            RuleFor(customer => customer.PostalCode)
                .NotEmpty()
                .Must(validatePostalCode)
                .WithMessage("Invalid Postal Code");
                
            RuleFor(customer => customer.Adress)
                .NotEmpty();
                
            RuleFor(customer => customer.Number)
                .NotEmpty();
        }
        
        public bool validateCpf(string cpf)
        {
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +        {
NotEmpty, entre outros já possuem mensagens padrões de resposta.

Rever tuas mensagens de formato inválido, elas não dizem ao usuário como deve ser o formato válido, então não ajudam muito.

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +            int[] multiplier1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
```suggestion
            if (cpf.All(character => character == cpf.First()))
                return false;
                
            int[] multiplier1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +                return false;
```suggestion
            
            cpf = cpf.FormatCpf();
            
            if (cpf.Length != 11)
                return false;
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +            return cpf.EndsWith(digit);
```suggestion
            for (int i = 0; i < 9; i++)
                sum += int.Parse(tempCpf[i].ToString()) * multiplier1[i];
                
            rest = sum % 11;
            
            if (rest < 2)
                rest = 0;                
            else
                rest = 11 - rest;
                
            digit = rest.ToString();
            tempCpf = tempCpf + digit;
            sum = 0;
            
            for (int i = 0; i < 10; i++)
                sum += int.Parse(tempCpf[i].ToString()) * multiplier2[i];
                
            rest = sum % 11;
            
            if (rest < 2)
                rest = 0;
            else
                rest = 11 - rest;
                
            digit = digit + rest.ToString();
            
            return cpf.EndsWith(digit);
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +            return System.Text.RegularExpressions.Regex.IsMatch(postalCode, ("[0-9]{5}-[0-9]{3}"));
```suggestion
            if (postalCode.Length == 8)
                postalCode = postalCode.Substring(0, 5) + "-" + postalCode.Substring(5, 3);
                
            return System.Text.RegularExpressions.Regex.IsMatch(postalCode, ("[0-9]{5}-[0-9]{3}"));
```

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +            return System.Text.RegularExpressions.Regex.IsMatch(postalCode, ("[0-9]{5}-[0-9]{3}"));
Como teu if só vai fazer uma coisa, não precisa das { }

2022-11-18 15:18 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
> +            return true;
```suggestion
            if (cellphone.Length < 10 || cellphone.Length > 11)
                return false;
                
            if (cellphone.Length == 11)  
                if (cellphone[2].ToString() != "9")
                    return false;
                    
            return true;
```

2022-11-18 16:09 UTC, guilhermeqmaia commented on CustomerApplication/Controllers/CustomerController.cs
> +            }
feito

2022-11-18 16:31 UTC, gregoryzimmerwarren approved these changes
Deixei só mais um comentário, mas como da minha parte acredito ser só isso já vou deixar aprovado.

2022-11-18 16:31 UTC, gregoryzimmerwarren commented on Data/Validators/CustomerValidator.cs
>          public bool validateCpf(string cpf)
```suggestion
        }
        
        public bool validateCpf(string cpf)
```

2022-11-18 16:51 UTC, guilhermeqmaia commented on Data/Validators/CustomerValidator.cs
>          public bool validateCpf(string cpf)
arrumei já, como na IDE fica uma mensagem de quantas referências tem aquele método eu nem vejo esses espaços faltando haha

2022-11-18 17:11 UTC, LucasPerinWarren commented on CustomerApplication/Controllers/CustomerController.cs
> +    {
Não vejo nenhuma classe "ControllerBase" no projeto, essa dependência esta correta?
```suggestion
    public class CustomerController
    {
```

2022-11-18 17:13 UTC, LucasPerinWarren commented on Data/Services/CustomerService.cs
> +using System.Linq;
```suggestion﻿
using Data.Entities;
using Data.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
```

2022-11-18 17:13 UTC, LucasPerinWarren commented on Data/Services/CustomerService.cs
> +using System.Linq;
```suggestion
﻿using Data.Entities;
using Data.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
```

2022-11-18 17:15 UTC, LucasPerinWarren commented on Data/Validators/CustomerValidator.cs
> +        {
```suggestion
        public bool IsValidPostalCode(string postalCode)
        {
```

2022-11-18 17:15 UTC, LucasPerinWarren commented on Data/Validators/CustomerValidator.cs
> +        {
```suggestion
        public bool IsValidCpf(string cpf)
        {
```

2022-11-18 17:16 UTC, LucasPerinWarren requested changes
Verificar Comentários

2022-11-18 17:21 UTC, LucasPerinWarren approved these changes

2022-11-18 17:53 UTC, santosclaudinei-warren approved these changes

2022-11-18 18:02 UTC, santosclaudinei-warren commented on Data/Entities/Customer.cs
> +using FluentValidation.Internal;
Não utilizado. Favor remover

2022-11-18 18:05 UTC, santosclaudinei-warren commented on Data/Entities/Customer.cs
> +
```suggestion
```
Remover linha em branco.

2022-11-18 18:06 UTC, santosclaudinei-warren commented on Data/Validators/CustomerValidator.cs
> +using System.Runtime.ConstrainedExecution;
```suggestion
```
Remover using não utilizado

2022-11-18 18:10 UTC, santosclaudinei-warren commented on Data/Validators/CustomerValidator.cs
> +            RuleFor(customer => customer.Adress)
```suggestion
            RuleFor(customer => customer.Address)
```

2022-11-18 18:11 UTC, santosclaudinei-warren commented on Data/Entities/Customer.cs
> +            string adress,
```suggestion
            string address,
```

2022-11-18 18:11 UTC, santosclaudinei-warren commented on Data/Entities/Customer.cs
> +            Adress= adress;
```suggestion
            Address= address;
```

2022-11-18 18:14 UTC, santosclaudinei-warren commented on Data/Validators/CustomerValidator.cs
> +        }
```suggestion
        public bool IsValidCellphone(string cellphone)
        {
            if (cellphone.Length < 10 || cellphone.Length > 11) return false;

            if (cellphone.Length == 11 && cellphone[2].ToString() != "9") return false;

            return true;
        }
```
Dica para eliminar um if dentro de outro e simplificar. Mas não é critério para aprovação.

2022-11-18 18:15 UTC, santosclaudinei-warren commented on Data/Utilities/StringExtensions.cs
> +
Usings nunca utilizados.

2022-11-18 18:16 UTC, santosclaudinei-warren commented on Data/Utilities/StringExtensions.cs
> +        }
```suggestion
        }
        
```

2022-11-21 14:54 UTC, viniciusoliveira-warren commented on Data/Services/CustomerService.cs
> +                throw new ArgumentNullException($"Customer for id: {id} was not found");
```suggestion
            var customer = _customers.FirstOrDefault(customer => customer.Id == id)
                ?? throw new ArgumentNullException($"Customer for id: {id} was not found");
```

2022-11-21 14:56 UTC, viniciusoliveira-warren approved these changes

2022-11-21 15:17 UTC, merged